11. Full Stack Application Development Capstone Project/CarDealerships/server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL

    # path for about view

    path(route='about/', view=views.about, name='about'),
    # path for contact us view
    path(route='contact/', view=views.contact, name='contact'),
    # path for signup form
    path(route='signup/', view=views.sign_up, name='signup'),
    # path for registration
    path(route='register/', view=views.register_request, name='register'),
    # path for login
    path(route='login/', view=views.login_request, name='login'),
    # path for logout
    path(route='logout/', view=views.logout_request, name='logout'),

    path(route='', view=views.get_dealerships, name='index'),

    # path for dealer reviews view
    path('dealer/<int:dealer_id>/', views.get_dealer_details, name='dealer_details'),

    path('review_form/<int:dealer_id>/', views.review_form, name='review_form'),
    # path for add a review view
    path('add_review/<int:dealer_id>/', views.add_review, name='add_review'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

11. Full Stack Application Development Capstone Project/CarDealerships/server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

11. Full Stack Application Development Capstone Project/CarDealerships/server/djangoapp/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.

# <HINT> Create a Car Make model `class CarMake(models.Model)`:
# - Name
# - Description
# - Any other fields you would like to include in car make model
# - __str__ method to print a car make object
class CarMake(models.Model):

    name = models.CharField(max_length=30)
    description = models.TextField()

    def __str__(self):  
        return self.name

# <HINT> Create a Car Model model `class CarModel(models.Model):`:
# - Many-To-One relationship to Car Make model (One Car Make has many Car Models, using ForeignKey field)
# - Name
# - Dealer id, used to refer a dealer created in cloudant database
# - Type (CharField with a choices argument to provide limited choices such as Sedan, SUV, WAGON, etc.)
# - Year (DateField)
# - Any other fields you would like to include in car model
# - __str__ method to print a car make object
class CarModel(models.Model):
    name = models.CharField(max_length=30)
    type_choices = (
        ('sedan', 'sedan'),
        ('SUV', 'SUV'),
        ('WAGON', 'WAGON'),
        ('coupé', 'coupé'),
        ('racing', 'racing'),
    )
    type = models.CharField(choices=type_choices, max_length=30)
    dealer_id = models.IntegerField()

    make = models.ForeignKey(CarMake, on_delete=models.CASCADE)

    def __str__(self):  
        return self.name

# <HINT> Create a plain Python class `CarDealer` to hold dealer data
class CarDealer:
    def __init__(self, address, city, full_name, id, lat, long, short_name, st, zip):
        # Dealer address
        self.address = address
        # Dealer city
        self.city = city
        # Dealer Full Name
        self.full_name = full_name
        # Dealer id
        self.id = id
        # Location lat
        self.lat = lat
        # Location long
        self.long = long
        # Dealer short name
        self.short_name = short_name
        # Dealer state
        self.st = st
        # Dealer zip
        self.zip = zip
    def __str__(self):
        return "Dealer name: " + self.full_name

# <HINT> Create a plain Python class `DealerReview` to hold review data

class DealerReview:
    def __init__(self, dealership, name, purchase, review, purchase_date, car_make, car_model, car_year, sentiment, id):
        self.dealership = dealership,
        self.name = name,
        self.purchase = purchase,
        self.review = review,
        self.purchase_date = purchase_date,
        self.car_make = car_make,
        self.car_model = car_model,
        self.car_year = car_year,
        self.sentiment = sentiment,
        self.id = id
    def __str__(self):
        return "Dealer name: " + self.full_name

11. Full Stack Application Development Capstone Project/CarDealerships/server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
# from .models import related models
from .models import CarDealer, CarMake, CarModel
# from .restapis import related methods
from .restapis import get_dealers_from_cf, get_dealer_reviews_from_cf, post_request, get_review_id
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.
def home(request):
    context = {}

    if request.method == 'GET':
        return render(request, '/index.html', context)
# Create an `about` view to render a static about page
def about(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/about.html', context)

# Create a `contact` view to return a static contact page
#def contact(request):
def contact(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/contact.html', context)

# Create a `signup` view to return a static signup page
#def contact(request):
def sign_up(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/signup.html', context)

# Create a `login_request` view to handle sign in request
# def login_request(request):
def login_request(request):

    error_message = None

    context = {}

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
    
        user = authenticate(request, username=username, password=password)
        print("Trying login...")
        if user:
            print("Found user, logging in")
            login(request, user)
            return redirect('..')
        else:
            print("User not found")
            error_message = "Invalid username or password. Please try again."
            return redirect('..')
    
    return render(request, 'djangoapp/index.html', {'error_message': error_message})
        

# Create a `logout_request` view to handle sign out request
# def logout_request(request):
def logout_request(request):
    if request.method == 'POST':
        logout(request)
        # Redirect to the desired page after logging out
        return redirect('..')  # Assuming 'home' is the name of your home page URL pattern
    # Handle other cases (GET request or invalid POST request)
    return redirect('..')  # Redirect to home page in other cases as well

# Create a `registration_request` view to handle sign up request
# def registration_request(request):
def register_request(request):
    context = {}

    if request.method == 'GET':
        return render(request, 'djangoapp/index.html', context)

    if request.method == 'POST':
        print("This was a post request!")
        username = request.POST['username']
        password = request.POST['password']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        
        existing_user = User.objects.filter(username=username).first()

        if existing_user:
            print("User already exists, trying again!")
            messages.error(request, 'User already exists. Please try again.')
            return redirect('../signup')
        else:
            print("New user, registering...")
            user = User.objects.create_user(username=username, password=password, first_name=first_name, last_name=last_name)
            login(request, user)
            return redirect('..')

    print("If successful registration of a new user, this shouldn't happen...")
    return render(request, "djangoapp/index.html", context)


# Update the `get_dealerships` view to render the index page with a list of dealerships
def get_dealerships(request):

    context = {}

    if request.method == "GET":
        url = "http://localhost:3300/dealerships"
        # Get dealers from the URL
        dealerships = get_dealers_from_cf(url)
        # Concat all dealer's short name
        context['dealerships'] = dealerships
        # Return a list of dealer short name
        return render(request, 'djangoapp/index.html', context)


# Create a `get_dealer_details` view to render the reviews of a dealer
# def get_dealer_details(request, dealer_id):
def get_dealer_details(request, dealer_id):

    context = {}
    dealership = get_dealers_from_cf(f"http://localhost:3300/dealerships?dealerId={dealer_id}")
    context['dealership'] = dealership[0].full_name
    context['dealership_id'] = dealership[0].id
    if request.method == "GET":
        url = f"http://localhost:5000/review/{dealer_id}"

        reviews = get_dealer_reviews_from_cf(url)

        context['reviews'] = reviews

        return render(request, 'djangoapp/dealer_details.html', context)


# go_to_review_form
def review_form(request, dealer_id):

    context = {
        "id": dealer_id,
    }

    return render(request, "djangoapp/add_review.html", context)


# Create a `add_review` view to submit a review
# def add_review(request, dealer_id):
def add_review(request, dealer_id):

    url = "http://localhost:5000/review"
    
    json_payload = {
        "dealership": dealer_id
    }

    json_payload['id'] = get_review_id()
    json_payload['name'] = request.user.first_name + " " + request.user.last_name
    json_payload['review'] = request.POST['review']
    json_payload['purchase'] = request.POST['purchase']
    if request.POST['purchase']:
        json_payload['purchase_date'] = datetime.utcnow().isoformat()
        json_payload['car_make'] = "BMW"
        json_payload['car_model'] = "M5"
        json_payload['car_year'] = 2020
    
    result = post_request(url, json_payload)

    print(result)

    dealer_details_url = reverse('djangoapp:dealer_details', kwargs={'dealer_id': dealer_id})

    return redirect(dealer_details_url)

    

11. Full Stack Application Development Capstone Project/CarDealerships/server/djangoapp/templates/djangoapp/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us | Best Car Dealership</title>
    <!-- Bootstrap CSS Link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Custom Styles (if needed) */
        .container { 
            border-top: 10px solid black;
            padding-top: 8%;
            border-left: 1px solid #000; /* Vertical line on the left */
            border-right: 3px solid #000; /* Vertical line on the right */
        }
        
        .additional-box {
            text-align: center; /* Center align the content inside the box */
        }

        img {
            max-width: 100%; /* Make sure the image doesn't exceed its parent container */
            height: auto; /* Maintain aspect ratio */
            margin-top: 20px; /* Add some margin between the text and the image */
            box-shadow: 2px 2px;
            border-radius: 10%;
        }

        .c img {
            max-width: 5%;
            height: 5%;
            margin-right: 2%;
            margin-top: .5%;
            box-shadow: 2px 2px;
            border-radius: 10%;
        }

        .c p {
            margin-right: 2%;
        }

        button {
            margin-top: .5%;
            height: 60%;
        }

        .nav-item:hover {
            font-weight: bold;
        }

        
    </style>
</head>

<body class="bg-secondary">
    <div class="conatiner bg-dark">
        <h1 class="text-white-50 bg-dark p-3">Best Car Dealership</h1>

    <!-- Add a nav bar here -->
        <nav class="navbar navbar-expand-lg navbar-light bg-dark d-flex justify-content-between">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-white-50" href="..">Home</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="">About <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white-50" href="../contact">Contact</a>
                    </li>
                    <!-- Add more navigation items as needed -->
                </ul>
            </div>
            <!-- {% if user.is_authenticated %} -->
            <div style="padding-right: 2%;" class="c d-flex justify-content-end g-4">
                <img src="https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/avatar-icon.png">
                <p class="lead text-white-50">{{user.username}}</p>
                <form method="post" action="{% url 'djangoapp:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn-white">Logout</button>
                </form>
            </div>
            <!-- {% else %} -->
            <div style="padding-right: 2%;">
                <form method="post" action="{% url 'djangoapp:login' %}">
                    {% csrf_token %}
                    <input class="input-group-sm" placeholder="username" type="text" name="username">
                    <input class="input-group-sm" placeholder="password" type="password" name="password">
                    <button type="submit" class="btn-outline-secondary">Login</button>
                </form>
                <a class="btn-outline-dark" href="../signup/">Sign Up</a>
            </div>
            <!-- {% endif %} -->
        </nav>
    </div>
    <div class="container mt-5 bg-white">
        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <div class="text-center mb-4">
                    <h1 class="display-4">Welcome to Best Cars Dealership</h1>
                    <p class="lead">Home to the best cars in North America. We sell domestic and imported cars at reasonable prices.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <div class="text-center mb-4">
                    <p class="text-secondary-emphasis">We are a top car seller in North America and are ready to serve you whenever you need it. Feel free to look around and contact us with any questions!</p>
                    <p class="text-secondary-emphasis">More text</p>
                    <img src="https://cdn.pixabay.com/photo/2019/07/07/14/03/fiat-500-4322521_1280.jpg">
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS and Popper.js (required for Bootstrap's JavaScript plugins) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

11. Full Stack Application Development Capstone Project/CarDealerships/server/djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>

</head>
<style>
    .container {
        margin: 0 auto;
        padding: 20px;
        border-left: 2px solid #000; /* Vertical line on the left */
        border-right: 2px solid #000; /* Vertical line on the right */
    }

    .additional-box {
        text-align: center; /* Center align the content inside the box */
    }

    .c img {
        max-width: 5%;
        height: 5%;
        margin-right: 2%;
        box-shadow: 2px 2px;
        border-radius: 10%;
    }

    .c p {
        margin-right: 2%;
    }

    button {
        margin-top: 0%;
        height: 60%;
    }

    .nav-item:hover {
        font-weight: bold;
    }

    body {
        background-image: url("https://cdn.pixabay.com/photo/2014/09/07/22/34/car-race-438467_640.jpg");
        background-size: cover;
    }

    .review-card {
            margin-top: 20px;
            margin-bottom: 20px;
            padding: 20px;
            background-color: white;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

    .review-card h3 {
        margin-bottom: 10px;
    }

    .review-card h4 {
        margin-top: 20px;
        margin-bottom: 10px;
    }

    .review-card input {
        margin-left: 20%;
        margin-bottom: 10px;
    }


</style>
    <body>
        <div class="bg-dark">
            <h1 class="text-white-50 bg-dark p-3">Best Car Dealership</h1>
        <!-- Add a nav bar here -->
            <nav class="navbar navbar-expand-lg navbar-light bg-dark d-flex justify-content-between">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-white" href="../..">Home<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white-50" href="../../about/">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white-50" href="../../contact/">Contact</a>
                        </li>
                        <!-- Add more navigation items as needed -->
                    </ul>
                </div>
                <!-- {% if user.is_authenticated %} -->
                <div style="padding-right: 2%;" class="c d-flex justify-content-end g-4">
                    <img src="https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/avatar-icon.png">
                    <p class="lead text-white-50">{{user.username}}</p>
                    <form method="post" action="{% url 'djangoapp:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn-white">Logout</button>
                    </form>
                </div>
                <!-- {% else %} -->
                <div style="padding-right: 2%;">
                    <form method="post" action="{% url 'djangoapp:login' %}">
                        {% csrf_token %}
                        <input class="input-group-sm" placeholder="username" type="text" name="username">
                        <input class="input-group-sm" placeholder="password" type="password" name="password">
                        <button type="submit" class="btn-outline-secondary">Login</button>
                    </form>
                    <a class="btn-outline-dark" href="signup/">Sign Up</a>
                </div>
                <!-- {% endif %} -->
            </nav>
        </div>
    <!--Add review form here -->
        <div>
            <form class="review-card" method="post" action="{% url 'djangoapp:add_review' id %}">
                {% csrf_token %}
                <h4>Write your review here:</h4>
                <textarea class="form-control" id="content" name="review" rows="2" required></textarea>
                <div class="d-flex">
                    <p>Check if you have made a purchase</p>
                    <input class="form-check-input" type="checkbox" name="purchase" id="purchasecheck">
                </div>
                <p>Select car if you've made a purchase:</p>
                <select>
                    <option>BMW M5 2020</option>

                </select><br>
                <button type="submit">Submit</button>
            </form>
        </div>
    </body>
</html>

11. Full Stack Application Development Capstone Project/CarDealerships/server/djangoapp/templates/djangoapp/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
    <body>
    <!--Add a registration form here -->
    </body>
</html>

11. Full Stack Application Development Capstone Project/CarDealerships/server/djangoapp/templates/djangoapp/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Best Car Dealership</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <style>
        h3 {
            text-align: center;
        }
        
        p {
            text-align: center;
            font-style: italic;
        }
        .container {
            padding-top: 10%;
            padding-bottom: 10%;
            background-color: #62676c; /* Light background color */
            border-radius: 10px; /* Rounded corners */
            box-shadow: 0px 0px 20px 0px rgb(15, 15, 15, 0.5); /* Box shadow for depth */
            max-width: 400px;
        }

        /* Styles for form elements inside the container */
        .container input[type="text"],
        .container input[type="password"] {
            width: 50%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ced4da;
            border-radius: 5px;
            font-size: 16px;
        }

        .container button {
            width: 50%;
            padding: 12px;
            background-color: #262c32; /* Bootstrap primary color */
            border: none;
            border-radius: 5px;
            color: white;
            font-size: 18px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .container button:hover {
            background-color: #71abe9; /* Darker shade on hover */
        }

        /* Additional styles for form labels if needed */
        .container label {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        /* Center the form within the container */
        .container form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .container::after {
            content: "";
            display: table;
            clear: both;
        }

        .additional-box {
            text-align: center; /* Center align the content inside the box */
        }

        .c img {
            max-width: 5%;
            height: 5%;
            margin-right: 2%;
            box-shadow: 2px 2px;
            border-radius: 10%;
        }

        .c p {
            margin-right: 2%;
        }

        button {
            margin-top: 0%;
            height: 60%;
        }

        .nav-item:hover {
            font-weight: bold;
        }

        body {
            background-color: cadetblue;
        }

        .background {
            background-image: url("https://cdn.pixabay.com/photo/2016/05/06/16/32/car-1376190_1280.jpg");
            background-size: cover;
        }
    </style>

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>My Django App</title>
        <!-- Bootstrap CSS Link -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>
    
    <body class="background">
        <div class="bg-dark">
            <h1 class="text-white-50 bg-dark p-3">Best Car Dealership</h1>
        <!-- Add a nav bar here -->
            <nav class="navbar navbar-expand-lg navbar-light bg-dark d-flex justify-content-between">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link text-white" href="..">Home<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white-50" href="../about/">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white-50" href="../contact/">Contact</a>
                        </li>
                        <!-- Add more navigation items as needed -->
                    </ul>
                </div>
                <!-- {% if user.is_authenticated %} -->
                <div style="padding-right: 2%;" class="c d-flex justify-content-end g-4">
                    <img src="https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/avatar-icon.png">
                    <p class="lead text-white-50">{{user.username}}</p>
                    <form method="post" action="{% url 'djangoapp:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn-white">Logout</button>
                    </form>
                </div>
                <!-- {% else %} -->
                <div style="padding-right: 2%;">
                    <form method="post" action="{% url 'djangoapp:login' %}">
                        {% csrf_token %}
                        <input class="input-group-sm" placeholder="username" type="text" name="username">
                        <input class="input-group-sm" placeholder="password" type="password" name="password">
                        <button type="submit" class="btn-outline-secondary">Login</button>
                    </form>
                    <p class="btn-outline-dark">Sign up</p>
                </div>
                <!-- {% endif %} -->
            </nav>
        </div>
        <div class="container">
            <h3>Welcome!</h3>
            <p>Please fill this form to get unlimited access to our site.</p>
            <form method="post" action="{% url 'djangoapp:register' %}" class="form-check-inline">
                {% csrf_token %}
                <input type="text" name="username" placeholder="username"><br>
                <input type="text" name="firstname" placeholder="first name"><br>
                <input type="text" name="lastname" placeholder="last name"><br>
                <input type="password" name="password" placeholder="*********"><br>
                <button type="submit">sign up</button>
            </form>
            {% if messages %}
                    {% for message in messages %}
                        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                    {% endfor %}
            {% endif %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    </body>
    
    </html>